# Generated by Django 4.1.6 on 2023-03-04 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=70)),
                ('class_description', models.CharField(max_length=250)),
                ('class_slug', models.SlugField()),
                ('class_imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='worktables/', verbose_name='Imagen')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktable_name', models.CharField(max_length=70)),
                ('worktable_imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='worktables/', verbose_name='Imagen')),
                ('worktable_slug', models.SlugField()),
                ('worktable_invite_url', models.CharField(max_length=8, null=True)),
                ('worktable_invite_url_expiration', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscriptions_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.class')),
                ('inscriptions_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='WorkTable_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.worktable'),
        ),
        migrations.AddField(
            model_name='class',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(max_length=250)),
                ('announcement_slug', models.SlugField()),
                ('announcement_username', models.CharField(max_length=70)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('announcement_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.class')),
                ('announcement_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('announcement_worktable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.worktable')),
            ],
        ),
    ]
